[phases]
setup = """
    python3 -m venv /opt/venv
    . /Scripts/activate
    pip install -r requirements.txt
"""
start = """
    . /Scripts/activate
    python app.py
"""

[variables]
HOST = "0.0.0.0"
PORT = "5000"

